### ISSUE TITLE
Compatibility with Adafruit Feather M0 or 32u4?

### ISSUE THREAD

**Issue by jbfink** [kc1awv/KISSLoRaTNC#1]
Hello Steve,

Was incredibly excited when I saw this repo -- I'm working on a project that involves LoRa. Do you know if this code will work on either the Adafruit [32u4 LoRa 900Mhz feather](https://www.adafruit.com/product/3078) or ideally the [M0 version](https://www.adafruit.com/product/3178)? Pretty sure the 32u4 will work as I think that's an existing target for you (although not in the feather form-factor) but the M0 would be wonderful as it's a little bit more beefy and capable. I don't have either version on hand -- was looking for something **just like KISSLoRaTNC** before I pulled the trigger, but if there's a good possibility it'll work I'll get my hands on them. Thanks!

**Comment by kc1awv** [comment]
Wow, I haven't been on this repo for a long time. I apologize for the delay.

The 32u4 and the M0 are different microcontrollers than the one on the Uno. I can't guarantee that this code will work there.
