### ISSUE TITLE
Standalone TNC + GPS + Bluetooth (For APRSdroid use)

### ISSUE THREAD

**Issue by jumpingbrowntrout** [kc1awv/KISSLoRaTNC#2]
Interested in this project. Just have a couple questions I am trying to figure out answers too.

Could I build a full stand alone APRS tnc devices with radio and gps using Arduino Uno + HamShield: LoRa Edition 144mhz + ublox neo-6m gps? I havent seen any mentioned about the gps use.

The other question I have is I see this project can interface will APRSdroid but is this via usb-otg OR can we add bluetooth module  HC-05/HC-06 to Arduino Uno and use APRSdroid?

**Comment by jumpingbrowntrout** [comment]
I find it strange that 144mhz isn't even a LoRa frequency. I wonder if this project event supports it?

**Comment by kc1awv** [comment]
I apologize that I have not reviewed this comment earlier.

If you're going to use APRSdroid, there's no need to add on a GPS, as your Android device may already have one. 

Adding in the libraries for a GPS to this code should be trivial, however. So long as all of the code still fits on the 328P.

The HamShield LoRA Edition has three options you can purchase, 2 m, 70 cm, and 33 cm.
